{{- if .Values.server.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chess-potato-ai-3000-web.serverSecretName" . }}
  labels:
    {{- include "chess-potato-ai-3000-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  CPAI3000_SECRET_KEY: {{ .Values.server.secretKey | quote }}
{{- end }}
