apiVersion: v1
kind: Service
metadata:
  name: {{ include "chess-potato-ai-3000-web.serverName" . }}
  labels:
    {{- include "chess-potato-ai-3000-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "chess-potato-ai-3000-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
