{{- if or .Values.server.secretKey .Values.server.ollama.bearerToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chess-potato-ai-3000-web.serverSecretName" . }}
  labels:
    {{- include "chess-potato-ai-3000-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.server.ollama.bearerToken }}
  OLLAMA_BEARER_TOKEN: {{ .Values.server.ollama.bearerToken | quote }}
  {{- end }}
  {{- if .Values.server.secretKey }}
  CPAI3000_SECRET_KEY: {{ .Values.server.secretKey | quote }}
  {{- end }}
{{- end }}
